# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"API_KEY": "01-baidu-ocr.ipynb",
         "SECRET_KEY": "01-baidu-ocr.ipynb",
         "OCR_URL": "01-baidu-ocr.ipynb",
         "TOKEN_URL": "01-baidu-ocr.ipynb",
         "baidu_fetch_token": "01-baidu-ocr.ipynb",
         "baidu_request": "01-baidu-ocr.ipynb",
         "baidu_ocr": "01-baidu-ocr.ipynb"}

modules = ["baidu_ocr.py"]

doc_url = "https://threefoldo.github.io/ocrbot/"

git_url = "https://github.com/threefoldo/ocrbot/tree/{branch}/"

def custom_doc_links(name): return None
